apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: safe
spec:
  version: {{ .TagName }}
  homepage: https://github.com/rumstead/kubectl-safe
  shortDescription: Prompts before running edit commands
  description: |
    This plugin allows users to confirm when they get prompted
    on certain kubectl commands.
  platforms:
  - selector:
      matchExpressions:
        - key: os
          operator: In
          values:
            - darwin
            - linux
            - windows
    {{addURIAndSha "https://github.com/rumstead/kubectl-safe/releases/{{ .TagName }}.tar.gz" .TagName }}
    bin: kubectl-safe